[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/hcl"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "v3-unstable"
  name = "gopkg.in/alecthomas/kingpin.v3-unstable"

[prune]
  go-tests = true
  unused-packages = true
